### ISSUE TITLE
Header row consumption?

### ISSUE THREAD

**Issue by metasoarous** [davidsantiago/clojure-csv#26]
Some tools (such as python `csv` module) support consuming headers, so that rows can be returned as dictionaries. Is this something you'd consider supporting? I'd be happy to either add this, or create my own project if you want to keep core functionality simple.

**Comment by davidsantiago** [comment]
What I like about this code is that it only interprets the CSV structure, and does no further interpretation of it. It gives and expects strings of the CSV cell contents, and that's it. Higher level ideas of what is in the CSV are better handled at the layer that interprets the CSV data. Hopefully this library makes writing those functions turn into a task that is only a few lines for most people. But there's no idea of serializing/deserializing here, by design.
